# Generated by Django 3.1.5 on 2021-04-27 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject_code', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('RollNumber', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('mail', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClassTimings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayNum', models.IntegerField(blank=True, null=True)),
                ('time', models.TimeField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time', to='ClassAPI.classroomtable')),
            ],
        ),
        migrations.AddField(
            model_name='classroomtable',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='createdBy', to='ClassAPI.teacher'),
        ),
        migrations.CreateModel(
            name='ClassroomStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='ClassAPI.classroomtable')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='ClassAPI.student')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('attachment', models.FileField(upload_to='uploads/')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ClassAPI.classroomtable')),
            ],
        ),
    ]
