# Generated by Django 3.1.5 on 2021-04-29 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClassAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubmissionText', models.TextField(blank=True, null=True)),
                ('SubmissionLink', models.TextField(blank=True, null=True)),
                ('MarkAsDone', models.IntegerField()),
                ('AssignmentNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='ClassAPI.assignment')),
                ('SubmittedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submittedBy', to='ClassAPI.student')),
            ],
        ),
    ]
