# Generated by Django 3.1.5 on 2021-04-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassAPI', '0002_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
