# Generated by Django 3.1.5 on 2021-05-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassAPI', '0004_assignmentsubmission_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
