# Generated by Django 3.1.5 on 2021-05-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassAPI', '0005_auto_20210501_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='attachment',
        ),
        migrations.AddField(
            model_name='assignment',
            name='attachmentLink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
